### ISSUE TITLE
Collaboration on the role ?

### ISSUE THREAD

**Issue by dmsimard** [robertdebock/ansible-role-ara#2]
Hi!

I'm the author of ARA -- I just came across this role and I like what I'm seeing. Great work :+1: 

We're actually in the process of building an awesome and tightly integrated role for ARA and I was curious if you'd be interested in collaborating ?
We're planning to leverage the role as an easy way of deploying ARA but also to integration test ARA itself.

The role can be found here: https://github.com/openstack/ansible-role-ara

Let me know if you'd like to chat !

**Comment by robertdebock** [comment]
Hi,

Yes, sounds great, i’m enjoying Ara so count me in!

Groet,

Robert de Bock

**Comment by dmsimard** [comment]
@robertdebock that's awesome!

Feel free to come ping me (dmsimard) on [IRC or Slack](https://github.com/openstack/ara#community-and-getting-help) whenever you'd like to chat so we can get started.

I'll close this issue :)
