### ISSUE TITLE
/etc/init.d/ara: 63: /etc/init.d/ara: Syntax error: Missing '))'\n

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-ara#3]
##### ISSUE TYPE
 - Bug Report

##### OS / ENVIRONMENT
Debian and Ubuntu

##### ACTUAL RESULTS
```
TASK [robertdebock.ara : start and enable ara] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "/etc/init.d/ara: 63: /etc/init.d/ara: Syntax error: Missing '))'\n"}
```

**Comment by dmsimard** [comment]
Are you working on sysvinit/upstart systems ?

FWIW we set up a systemd unit file in the [other role](https://github.com/openstack/ansible-role-ara/blob/master/tasks/embedded/standalone.yml).

**Comment by robertdebock** [comment]
Thanks @dmsimard , this was an issue with a SystemV init script. Seems to be resolved.
